services:
  - type: web
    name: spotify-lyrics-zh
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: SESSION_SECRET
        generateValue: true
